<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsTrimmable>true</IsTrimmable>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Blocks.Net.DataTypes\Blocks.Net.DataTypes.csproj" />
      <ProjectReference Include="..\Data\Blocks.Net.Data.Vanilla\Blocks.Net.Data.Vanilla.csproj" />
      <ProjectReference Include="..\Network\Blocks.Net.Packets\Blocks.Net.Packets.csproj" />
      <ProjectReference Include="..\Utilities\Blocks.Net.Nbt\Blocks.Net.Nbt.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="RegistryEntries\" />
    </ItemGroup>

</Project>
